"use server";
import { revalidatePath } from "next/cache";
import { getAuthenticatedClaims } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
export type ProjectMemberState = { status: "idle" | "error" | "success"; message?: string };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function change(formData: FormData, rpc: "request_project_access" | "submit_project_work") { if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." } satisfies ProjectMemberState; const id = formData.get("project_id"); if (typeof id !== "string" || !UUID.test(id)) return { status: "error", message: "Invalid project." } satisfies ProjectMemberState; const supabase = await createClient(); const { error } = await supabase.rpc(rpc, { p_project_id: id }); if (error) return { status: "error", message: rpc === "request_project_access" ? "This project is not accepting requests." : "Your work cannot be submitted yet." } satisfies ProjectMemberState; revalidatePath("/member/projects"); revalidatePath("/admin/projects"); return { status: "success", message: rpc === "request_project_access" ? "Access requested." : "Work submitted for review." } satisfies ProjectMemberState; }
export async function requestProjectAccess(_: ProjectMemberState, formData: FormData) { return change(formData, "request_project_access"); }
export async function submitProjectWork(_: ProjectMemberState, formData: FormData) { return change(formData, "submit_project_work"); }
function clean(value: FormDataEntryValue | null, max: number, required = false) { const text = typeof value === "string" ? value.trim().replace(/\s+/g, " ") : ""; return (required && !text) || text.length > max ? null : text; }
function slug(title: string) { return `${title.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 100) || "project"}-${crypto.randomUUID().slice(0, 8)}`; }
export async function createMemberProject(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> {
  if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." };
  const title = clean(formData.get("title"), 160, true); const category = clean(formData.get("category"), 80, true); const description = clean(formData.get("description"), 2000);
  const recruitment = formData.get("recruitment_mode"); const capacityValue = formData.get("team_capacity"); const capacity = typeof capacityValue === "string" && capacityValue ? Number(capacityValue) : null;
  const technologies = typeof formData.get("technologies") === "string" ? [...new Set((formData.get("technologies") as string).split(",").map((item) => item.trim()).filter(Boolean))].slice(0, 12) : [];
  if (!title || !category || description === null || !["open", "invite_only", "not_recruiting"].includes(String(recruitment)) || (capacity !== null && (!Number.isInteger(capacity) || capacity < 1 || capacity > 100)) || technologies.some((item) => item.length > 60)) return { status: "error", message: "Check the project details." };
  const supabase = await createClient(); const { error } = await supabase.rpc("create_project_v1", { p_title: title, p_slug: slug(title), p_category: category, p_description: description, p_technologies: technologies, p_recruitment_mode: String(recruitment), p_team_capacity: capacity });
  if (error) return { status: "error", message: "The project could not be created." }; revalidatePath("/member/projects"); return { status: "success", message: "Draft project created. You are its owner." };
}
export async function requestProjectJoin(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> {
  if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." }; const id = formData.get("project_id"); const contribution = clean(formData.get("contribution"), 120) ?? ""; const message = clean(formData.get("message"), 1000) ?? "";
  if (typeof id !== "string" || !UUID.test(id)) return { status: "error", message: "Invalid project." }; const supabase = await createClient(); const { error } = await supabase.rpc("request_project_join", { p_project_id: id, p_contribution: contribution, p_message: message });
  if (error) return { status: "error", message: "This project is not accepting your request." }; revalidatePath("/member/projects"); revalidatePath("/projects"); return { status: "success", message: "Join request sent." };
}
export async function submitProjectForReview(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> { if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." }; const id = formData.get("project_id"); if (typeof id !== "string" || !UUID.test(id)) return { status: "error", message: "Invalid project." }; const { error } = await (await createClient()).rpc("submit_project_for_review", { p_project_id: id }); if (error) return { status: "error", message: "This project cannot be submitted right now." }; revalidatePath("/member/projects"); revalidatePath("/admin/projects"); return { status: "success", message: "Project submitted for review." }; }
async function workspaceRpc(formData: FormData, rpc: "withdraw_project_join_request" | "resolve_project_join_request" | "transfer_project_ownership") { if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." } satisfies ProjectMemberState; const supabase = await createClient(); let error; if (rpc === "withdraw_project_join_request") { const requestId = formData.get("request_id"); if (typeof requestId !== "string" || !UUID.test(requestId)) return { status: "error", message: "Invalid request." }; ({ error } = await supabase.rpc(rpc, { p_request_id: requestId })); } else if (rpc === "resolve_project_join_request") { const requestId = formData.get("request_id"); const approve = formData.get("approve") === "true"; if (typeof requestId !== "string" || !UUID.test(requestId)) return { status: "error", message: "Invalid request." }; ({ error } = await supabase.rpc(rpc, { p_request_id: requestId, p_approve: approve })); } else { const projectId = formData.get("project_id"); const ownerId = formData.get("new_owner_id"); if (typeof projectId !== "string" || typeof ownerId !== "string" || !UUID.test(projectId) || !UUID.test(ownerId)) return { status: "error", message: "Invalid ownership transfer." }; ({ error } = await supabase.rpc(rpc, { p_project_id: projectId, p_new_owner_id: ownerId })); } if (error) return { status: "error", message: "This action could not be applied. The project may have changed." }; revalidatePath("/member/projects"); revalidatePath("/admin/projects"); return { status: "success", message: rpc === "transfer_project_ownership" ? "Ownership transferred." : "Team request updated." }; }
export async function withdrawProjectJoinRequest(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> { return (await workspaceRpc(formData, "withdraw_project_join_request")) as ProjectMemberState; }
export async function resolveProjectJoinRequest(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> { return (await workspaceRpc(formData, "resolve_project_join_request")) as ProjectMemberState; }
export async function transferProjectOwnership(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> { return (await workspaceRpc(formData, "transfer_project_ownership")) as ProjectMemberState; }
export async function updateMemberProject(_: ProjectMemberState, formData: FormData): Promise<ProjectMemberState> { if (!(await getAuthenticatedClaims())?.sub) return { status: "error", message: "Please sign in first." }; const id = formData.get("project_id"); const title = clean(formData.get("title"), 160, true); const category = clean(formData.get("category"), 80, true); const description = clean(formData.get("description"), 2000); const stage = formData.get("build_stage"); const recruitment = formData.get("recruitment_mode"); const capacityText = formData.get("team_capacity"); const capacity = typeof capacityText === "string" && capacityText ? Number(capacityText) : null; const repository = clean(formData.get("repository_url"), 500); const demo = clean(formData.get("demo_url"), 500); const technologies = typeof formData.get("technologies") === "string" ? [...new Set((formData.get("technologies") as string).split(",").map((value) => value.trim()).filter(Boolean))].slice(0, 12) : []; if (typeof id !== "string" || !UUID.test(id) || !title || !category || description === null || repository === null || demo === null || !["idea","building","prototype","shipped"].includes(String(stage)) || !["open","invite_only","not_recruiting"].includes(String(recruitment)) || (capacity !== null && (!Number.isInteger(capacity) || capacity < 1 || capacity > 100)) || technologies.some((item) => item.length > 60)) return { status: "error", message: "Check the project details." }; const { error } = await (await createClient()).rpc("update_project_v1", { p_project_id: id, p_title: title, p_category: category, p_description: description, p_technologies: technologies, p_build_stage: String(stage), p_recruitment_mode: String(recruitment), p_team_capacity: capacity, p_repository_url: repository || null, p_demo_url: demo || null }); if (error) return { status: "error", message: "The project cannot be edited in its current state." }; revalidatePath("/member/projects"); return { status: "success", message: "Project updated." }; }
