"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";
import { getProjectId, makeProjectSlug, projectUpdate, validateProjectInput } from "@/lib/validation/admin-projects";

export type ProjectFormState = { status: "idle" | "error" | "success"; message?: string };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function adminClient() { const claims = await requireAdmin(); return { claims, supabase: await createClient() }; }
function revalidateProjects() { revalidatePath("/admin/projects"); revalidatePath("/member/projects"); revalidatePath("/projects"); revalidatePath("/explore"); }
export async function createProject(_: ProjectFormState, formData: FormData): Promise<ProjectFormState> { const admin = await adminClient(); const input = validateProjectInput(formData); if ("error" in input) return { status: "error", message: input.error }; const { error } = await admin.supabase.rpc("create_project_v1", { p_title: input.data.title, p_slug: makeProjectSlug(input.data.title), p_category: input.data.category, p_description: input.data.description ?? "", p_technologies: input.data.technologies ?? [], p_recruitment_mode: "open", p_team_capacity: null }); if (error) return { status: "error", message: "The project could not be created." }; revalidateProjects(); return { status: "success", message: "Draft project created with you as owner." }; }
export async function updateProject(_: ProjectFormState, formData: FormData): Promise<ProjectFormState> { const admin = await adminClient(); const id = getProjectId(formData.get("project_id")); const input = validateProjectInput(formData); if (!id || "error" in input) return { status: "error", message: "error" in input ? input.error : "Invalid project." }; const { error } = await admin.supabase.from("projects").update(projectUpdate(input.data)).eq("id", id); if (error) return { status: "error", message: "The project could not be updated." }; revalidateProjects(); return { status: "success", message: "Project updated." }; }
export async function reviewProjectMember(_: ProjectFormState, formData: FormData): Promise<ProjectFormState> { const admin = await adminClient(); const projectId = formData.get("project_id"); const profileId = formData.get("profile_id"); const action = formData.get("action"); if (typeof projectId !== "string" || typeof profileId !== "string" || !UUID.test(projectId) || !UUID.test(profileId) || typeof action !== "string") return { status: "error", message: "Invalid team review." }; const { error } = await admin.supabase.rpc("review_project_member", { p_project_id: projectId, p_profile_id: profileId, p_action: action }); if (error) return { status: "error", message: "The team review could not be applied." }; revalidateProjects(); return { status: "success", message: "Team status updated." }; }
export async function reviewProjectPublication(_: ProjectFormState, formData: FormData): Promise<ProjectFormState> { const admin = await adminClient(); const projectId = formData.get("project_id"); const decision = formData.get("decision"); const feedback = formData.get("feedback"); if (typeof projectId !== "string" || !UUID.test(projectId) || typeof decision !== "string" || !["approved", "changes_requested", "archived"].includes(decision) || (typeof feedback === "string" && feedback.length > 2000)) return { status: "error", message: "Invalid project review." }; const { error } = await admin.supabase.rpc("review_project_publication", { p_project_id: projectId, p_decision: decision, p_feedback: typeof feedback === "string" ? feedback.trim() : "" }); if (error) return { status: "error", message: "The review could not be applied; the project may have changed." }; revalidateProjects(); return { status: "success", message: "Project review recorded." }; }
export async function recoverProjectOwnership(_: ProjectFormState, formData: FormData): Promise<ProjectFormState> { const admin = await adminClient(); const projectId = formData.get("project_id"); const ownerId = formData.get("new_owner_id"); const reason = formData.get("reason"); if (typeof projectId !== "string" || typeof ownerId !== "string" || !UUID.test(projectId) || !UUID.test(ownerId) || (typeof reason === "string" && reason.length > 1000)) return { status: "error", message: "Invalid ownership recovery." }; const { error } = await admin.supabase.rpc("recover_project_ownership", { p_project_id: projectId, p_new_owner_id: ownerId, p_reason: typeof reason === "string" ? reason.trim() : "" }); if (error) return { status: "error", message: "Recovery could not be applied." }; revalidateProjects(); return { status: "success", message: "Ownership recovered and audited." }; }
