import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Code2, MessageCircleHeart, Rocket, UsersRound } from "lucide-react";
import { getPublicCommunitySnapshot } from "@/lib/services/community";

const contributionWays = [
  { icon: BookOpen, title: "Share a useful note", detail: "Turn a fresh lesson into a trail someone else can follow." },
  { icon: MessageCircleHeart, title: "Give thoughtful feedback", detail: "Help a project move forward with a question, test, or perspective." },
  { icon: UsersRound, title: "Bring a collaborator", detail: "Invite someone curious and make the next build a little less lonely." },
];
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)); }

export default async function ExplorePage() {
  const snapshot = await getPublicCommunitySnapshot().catch(() => null);
  const challenges = snapshot?.challenges ?? [];
  const projects = snapshot?.projects ?? [];
  const events = snapshot?.events.filter((event) => event.status === "upcoming") ?? [];
  return <><section className="explore-hero"><div><div className="eyebrow">The AWS ISLEC ecosystem</div><h1>Find the thread<br />you want to <span>pull.</span></h1><p>Explore a community where learning becomes practice, practice becomes projects, and every project gives the next person somewhere to begin.</p><div className="hero-actions"><Link className="button" href="/join">Join the community <ArrowRight size={16} /></Link><Link className="button button-secondary" href="/member">Open member workspace</Link></div></div><aside className="explore-pulse"><div className="explore-pulse-header"><span className="eyebrow">Published community work</span></div><div className="explore-pulse-stat"><strong>{projects.length}</strong><span>projects ready<br />to explore</span></div><div className="explore-pulse-list"><div><Code2 size={15} /><span>{challenges.length} published challenges</span></div><div><CalendarDays size={15} /><span>{events.length} upcoming events</span></div></div></aside></section>
  <section className="explore-section explore-paths"><div className="explore-section-heading"><div><div className="eyebrow">Choose a direction</div><h2>Learn it. Then make it useful.</h2></div></div>{snapshot === null ? <p className="muted">The community catalogue is unavailable right now.</p> : <div className="explore-path-grid">{challenges.slice(0, 3).map((challenge, index) => <article className="explore-path-card" key={challenge.id}><div className="explore-card-top"><span className="explore-path-icon"><Rocket size={19} /></span><span className="tag">0{index + 1} / {challenge.level}</span></div><h3>{challenge.title}</h3><p>{challenge.detail}</p><div className="explore-card-foot"><span>+{challenge.points} builder points</span><Link href="/member/learn">Explore <ArrowRight size={15} /></Link></div></article>)}</div>}</section>
  <section className="explore-section explore-work"><div className="explore-section-heading"><div><div className="eyebrow">Built in the open</div><h2>See what people are making.</h2></div><Link className="section-action" href="/member/projects">Visit project studio <ArrowRight size={14} /></Link></div><div className="explore-projects">{projects.slice(0, 3).map((project) => <article className="explore-project" key={project.id}><div className="explore-project-mark"><Code2 size={22} /></div><div className="explore-project-copy"><span className="eyebrow">{project.category} / {project.status}</span><h3>{project.title}</h3><p>{project.description}</p></div><div className="explore-project-progress"><strong>{project.progress}%</strong><div className="progress-track"><div className="progress-value" style={{ width: `${project.progress}%` }} /></div></div></article>)}</div></section>
  <section className="explore-section explore-events"><div className="explore-section-heading"><div><div className="eyebrow">Make room to meet</div><h2>A reason to show up.</h2></div></div><div className="explore-event-grid">{events.slice(0, 3).map((event) => <article className="explore-event" key={event.id}><span className="explore-event-date">{formatDate(event.starts_at)}</span><div><span className="tag">{event.event_type}</span><h3>{event.title}</h3></div><Link href="/member/events" className="explore-event-link"><CalendarDays size={18} /></Link></article>)}</div></section>
  <section className="explore-contribute"><div className="explore-contribute-intro"><div className="eyebrow">There is room for your point of view</div><h2>A community gets stronger when people leave something useful behind.</h2><Link className="button" href="/join">Find your place <ArrowRight size={16} /></Link></div><div className="explore-contribution-list">{contributionWays.map(({ icon: Icon, title, detail }) => <div key={title}><span><Icon size={20} /></span><div><h3>{title}</h3><p>{detail}</p></div></div>)}</div></section></>;
}
