"use client";
import { useActionState } from "react";
import { FolderKanban, Pencil, UsersRound } from "lucide-react";
import { createProject, reviewProjectMember, updateProject } from "@/app/admin/projects/actions";
import type { ProjectFormState } from "@/app/admin/projects/actions";
import type { AdminProject } from "@/lib/services/projects";
const initialProjectFormState: ProjectFormState = { status: "idle" };
function Fields({ project }: { project?: AdminProject }) { return <div className="admin-event-fields"><label>Title<input name="title" required maxLength={160} defaultValue={project?.title} /></label><label>Category<input name="category" required maxLength={80} defaultValue={project?.category} /></label><label>Status<select name="status" defaultValue={project?.status ?? "in_progress"}><option value="in_progress">In progress</option><option value="shipped">Shipped</option><option value="archived">Archived</option></select></label><label>Progress<input name="progress" type="number" min="0" max="100" defaultValue={project?.progress ?? 0} /></label><label className="admin-event-field-wide">Technologies<input name="technologies" defaultValue={project?.technologies.join(", ") ?? ""} placeholder="Lambda, DynamoDB" /></label><label className="admin-event-publish"><input name="is_published" type="checkbox" defaultChecked={project?.is_published ?? false} style={{ width: "auto", minHeight: "auto" }} />Published for discovery</label><label className="admin-event-field-wide">Description<textarea name="description" maxLength={2000} defaultValue={project?.description ?? ""} /></label></div>; }
function Form({ project }: { project?: AdminProject }) { const [state, action, pending] = useActionState(project ? updateProject : createProject, initialProjectFormState); return <details className={project ? "admin-event-edit" : "admin-event-create"}><summary>{project ? <><Pencil size={15} />Edit</> : <><FolderKanban size={17} />Create project</>}</summary><form action={action}>{project ? <input type="hidden" name="project_id" value={project.id} /> : null}<Fields project={project} /><div className="admin-event-actions"><button className="button" disabled={pending}>{pending ? "Saving…" : project ? "Save changes" : "Create project"}</button><p className={`admin-event-message ${state.status}`}>{state.message}</p></div></form></details>; }
function Team({ project }: { project: AdminProject }) { const [state, action, pending] = useActionState(reviewProjectMember, initialProjectFormState); return <details className="admin-event-attendees"><summary>{project.members.length} team request{project.members.length === 1 ? "" : "s"}</summary>{project.members.map((member) => <div className="admin-event-attendee" key={member.profile_id}><div><strong>{member.fullName}</strong><span>{member.handle} · {member.status}</span></div>{member.status === "requested" ? <form action={action}><input type="hidden" name="project_id" value={project.id} /><input type="hidden" name="profile_id" value={member.profile_id} /><button className="button button-secondary" name="action" value="approve_request" disabled={pending}>Approve</button><button className="button button-secondary" name="action" value="decline_request" disabled={pending}>Decline</button></form> : member.status === "submitted" ? <form action={action}><input type="hidden" name="project_id" value={project.id} /><input type="hidden" name="profile_id" value={member.profile_id} /><button className="button button-secondary" name="action" value="complete_submission" disabled={pending}>Complete</button><button className="button button-secondary" name="action" value="return_submission" disabled={pending}>Return</button></form> : <span className="tag">{member.status}</span>}</div>)}{state.message ? <p className={`admin-event-message ${state.status}`}>{state.message}</p> : null}</details>; }
export function ProjectManagement({ projects }: { projects: AdminProject[] }) { return <section className="admin-events"><div className="admin-directory-head"><div><div className="eyebrow">Project studio</div><h2>Projects, in motion.</h2><p>Create, publish, and review the community’s project work.</p></div><span className="admin-directory-icon"><FolderKanban size={21} /></span></div><Form />{projects.map((project) => <article className="admin-event-row" key={project.id}><div className="admin-event-main"><div><span className="tag">{project.category}</span><span className="admin-event-status">{project.status}</span><span className="admin-event-status">{project.is_published ? "published" : "draft"}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="admin-event-meta"><span>{project.progress}% complete</span><span><UsersRound size={14} />{project.members.length} team records</span></div><Team project={project} /></div><Form project={project} /></article>)}</section>; }
